server:
  port: 8080
  servlet:
    context-path: /clients
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE